# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Build Jekyll site to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build Jekyll
        uses: jerryjvl/jekyll-build-action@v1
  
      - name: XDTesting Print Directory Structure
        uses: FiorelaCiroku/XDTesting-Print-Directory-Structure@v1.0.2
            

  # Deployment job
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: XDTesting Print Directory Structure
        uses: FiorelaCiroku/XDTesting-Print-Directory-Structure@v1.0.2
  #    
  #    - uses: actions/checkout@v4
  #    
  #    - name: Deploy to ENS server
  #      id: deployment        
  #      uses: appleboy/scp-action@v0.1.7
  #      with:
  #        host: ${{ secrets.HOST }}
  #        username: ${{ secrets.USERNAME }}
  #        password: ${{ secrets.PASSWORD }}
  #        port: ${{ secrets.PORT }}
  #        source: "tests/a.txt,tests/b.txt"
  #        target: your_server_target_folder_path
